[package]
name = "linear_regression"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = '*'
ndarray = "0.15"

[[bin]]
name = "revised"
path = "src/revised/main.rs"

[[bin]]
name = "performance"
path = "src/performance/main.rs"