[package]
name = "naive_bayes_revised"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
ndarray = "0.15"
rand = "0.8"

[[bin]]
name = "revised"
path = "src/revised/main.rs"

[[bin]]
name = "performance"
path = "src/performance/main.rs"